apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.4.240-192.168.4.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pihole-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - pihole-pool
